# fly.toml app configuration file generated for trading-webhook on 2023-08-01T16:26:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trading-webhook"
primary_region = "scl"

[env]
  SPRING_DATASOURCE_PASSWORD = "u2nDqbi3Jr6zAa4"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://gacituacompanypostgres.internal:5432/gacituadb"
  SPRING_DATASOURCE_USERNAME = "postgres"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
